### PR TITLE
add more browsers to browserstack

### PR DESCRIPTION
**Pull request by darlanmendonca**
we need add more browsers for browserstack, in multiple operational systems (windows, linux, mac)

this PR add all browsers that we want support

### CODE REVIEW

**Comment by darlanmendonca** [comment]
@alencar13 which browsers we need?

I thinking ONLY latest OS's and browsers

- Chrome Windows
- Firefox Linux
- Safari Mac

later, we can add support to more, but now, to reduce the size of work, I believe is better focus in the latest only

agree? I forget anyone?

**Comment by darlanmendonca** [comment]
the last commit works, run in chrome Windows, but broke tests because Windows have a scroll in render. Is the same problem in LInux that you show me @alencar13 in https://github.com/darlanmendonca/chai-style/pull/4. When we merge your PR, the tests will return success

**Comment by alencar13** [comment]
I agree use these browsers.

**Comment by darlanmendonca** [comment]
perfect!!, merging

**Pull request merged**
